# DB Config
spring.datasource.url=jdbc:postgresql://localhost:5432/location_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Import settings
import.batch-size=100